language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - pip install pip --upgrade;
  - pip install -r requirements.txt;

install:
  - python setup.py install;

script:
  - flake8 ./;
  - python -m pytest --pyargs altair;
