language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  matrix:
  - BUILD_TYPE="test"

matrix:
  include:
  - python: 2.7  # 2.7 is required for node-gyp used below
    env: BUILD_TYPE="docs"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda update conda
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION pytest
  - source activate testenv
  - conda install --file requirements.txt
  - if [[ $BUILD_TYPE == 'docs' ]]; then
       conda install --file doc/requirements.txt;
       sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++;
       npm install canvas vega vega-lite;
    fi

install:
  - python setup.py install

script:
  - if [[ $BUILD_TYPE == 'test' ]]; then
       python -m pytest altair --doctest-modules;
    elif [[ $BUILD_TYPE == 'docs' ]]; then
       cd doc && make html;
    fi
